version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: go-rpg:dev
    container_name: go-rpg
    ports:
      - "8000:8000"
    volumes:
      - ./:/code