// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/character.proto

package character

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Character_Race int32

const (
	Character_HUMAN Character_Race = 0
	Character_ELF   Character_Race = 1
	Character_DWARF Character_Race = 2
	Character_ORC   Character_Race = 3
)

// Enum value maps for Character_Race.
var (
	Character_Race_name = map[int32]string{
		0: "HUMAN",
		1: "ELF",
		2: "DWARF",
		3: "ORC",
	}
	Character_Race_value = map[string]int32{
		"HUMAN": 0,
		"ELF":   1,
		"DWARF": 2,
		"ORC":   3,
	}
)

func (x Character_Race) Enum() *Character_Race {
	p := new(Character_Race)
	*p = x
	return p
}

func (x Character_Race) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Character_Race) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_character_proto_enumTypes[0].Descriptor()
}

func (Character_Race) Type() protoreflect.EnumType {
	return &file_proto_character_proto_enumTypes[0]
}

func (x Character_Race) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Character_Race.Descriptor instead.
func (Character_Race) EnumDescriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{0, 0}
}

type Character_Class int32

const (
	Character_HUNTER  Character_Class = 0
	Character_WARRIOR Character_Class = 1
	Character_MAGE    Character_Class = 2
)

// Enum value maps for Character_Class.
var (
	Character_Class_name = map[int32]string{
		0: "HUNTER",
		1: "WARRIOR",
		2: "MAGE",
	}
	Character_Class_value = map[string]int32{
		"HUNTER":  0,
		"WARRIOR": 1,
		"MAGE":    2,
	}
)

func (x Character_Class) Enum() *Character_Class {
	p := new(Character_Class)
	*p = x
	return p
}

func (x Character_Class) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Character_Class) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_character_proto_enumTypes[1].Descriptor()
}

func (Character_Class) Type() protoreflect.EnumType {
	return &file_proto_character_proto_enumTypes[1]
}

func (x Character_Class) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Character_Class.Descriptor instead.
func (Character_Class) EnumDescriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{0, 1}
}

type Character struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Health int32           `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
	Race   Character_Race  `protobuf:"varint,3,opt,name=race,proto3,enum=character.Character_Race" json:"race,omitempty"`
	Class  Character_Class `protobuf:"varint,4,opt,name=class,proto3,enum=character.Character_Class" json:"class,omitempty"`
}

func (x *Character) Reset() {
	*x = Character{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_character_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{0}
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Character) GetRace() Character_Race {
	if x != nil {
		return x.Race
	}
	return Character_HUMAN
}

func (x *Character) GetClass() Character_Class {
	if x != nil {
		return x.Class
	}
	return Character_HUNTER
}

type CharData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Char *Character `protobuf:"bytes,2,opt,name=char,proto3,oneof" json:"char,omitempty"`
}

func (x *CharData) Reset() {
	*x = CharData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_character_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharData) ProtoMessage() {}

func (x *CharData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharData.ProtoReflect.Descriptor instead.
func (*CharData) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{1}
}

func (x *CharData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CharData) GetChar() *Character {
	if x != nil {
		return x.Char
	}
	return nil
}

type Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details string     `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	Char    *Character `protobuf:"bytes,2,opt,name=char,proto3,oneof" json:"char,omitempty"`
}

func (x *Info) Reset() {
	*x = Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_character_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{2}
}

func (x *Info) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Info) GetChar() *Character {
	if x != nil {
		return x.Char
	}
	return nil
}

type DB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db *string `protobuf:"bytes,1,opt,name=db,proto3,oneof" json:"db,omitempty"`
}

func (x *DB) Reset() {
	*x = DB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_character_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB) ProtoMessage() {}

func (x *DB) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB.ProtoReflect.Descriptor instead.
func (*DB) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{3}
}

func (x *DB) GetDb() string {
	if x != nil && x.Db != nil {
		return *x.Db
	}
	return ""
}

var File_proto_character_proto protoreflect.FileDescriptor

var file_proto_character_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x22, 0xf4, 0x01, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x2d, 0x0a, 0x04,
	0x72, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x2e, 0x52, 0x61, 0x63, 0x65, 0x52, 0x04, 0x72, 0x61, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x2e, 0x0a,
	0x04, 0x52, 0x61, 0x63, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x55, 0x4d, 0x41, 0x4e, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x45, 0x4c, 0x46, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x57, 0x41,
	0x52, 0x46, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x52, 0x43, 0x10, 0x03, 0x22, 0x2a, 0x0a,
	0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x55, 0x4e, 0x54, 0x45, 0x52,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x52, 0x49, 0x4f, 0x52, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x02, 0x22, 0x52, 0x0a, 0x08, 0x43, 0x68, 0x61,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x63, 0x68, 0x61,
	0x72, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x22, 0x58, 0x0a,
	0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x2d, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x63, 0x68, 0x61, 0x72, 0x88, 0x01, 0x01, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x22, 0x20, 0x0a, 0x02, 0x44, 0x42, 0x12, 0x13, 0x0a,
	0x02, 0x64, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x64, 0x62, 0x88,
	0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x64, 0x62, 0x32, 0x83, 0x02, 0x0a, 0x0a, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x14, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x1a, 0x0f, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x03, 0x47, 0x65, 0x74,
	0x12, 0x13, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x13, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x2e, 0x43, 0x68, 0x61, 0x72, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0f, 0x2e, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33, 0x0a, 0x06, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x2e, 0x43, 0x68, 0x61, 0x72, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x14, 0x2e, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12,
	0x2e, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x42, 0x1a, 0x13, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x44, 0x61, 0x74, 0x61, 0x30, 0x01, 0x42,
	0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_character_proto_rawDescOnce sync.Once
	file_proto_character_proto_rawDescData = file_proto_character_proto_rawDesc
)

func file_proto_character_proto_rawDescGZIP() []byte {
	file_proto_character_proto_rawDescOnce.Do(func() {
		file_proto_character_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_character_proto_rawDescData)
	})
	return file_proto_character_proto_rawDescData
}

var file_proto_character_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_character_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_character_proto_goTypes = []interface{}{
	(Character_Race)(0),  // 0: character.Character.Race
	(Character_Class)(0), // 1: character.Character.Class
	(*Character)(nil),    // 2: character.Character
	(*CharData)(nil),     // 3: character.CharData
	(*Info)(nil),         // 4: character.Info
	(*DB)(nil),           // 5: character.DB
}
var file_proto_character_proto_depIdxs = []int32{
	0, // 0: character.Character.race:type_name -> character.Character.Race
	1, // 1: character.Character.class:type_name -> character.Character.Class
	2, // 2: character.CharData.char:type_name -> character.Character
	2, // 3: character.Info.char:type_name -> character.Character
	2, // 4: character.Characters.Create:input_type -> character.Character
	3, // 5: character.Characters.Get:input_type -> character.CharData
	3, // 6: character.Characters.Delete:input_type -> character.CharData
	3, // 7: character.Characters.Update:input_type -> character.CharData
	5, // 8: character.Characters.GetAll:input_type -> character.DB
	4, // 9: character.Characters.Create:output_type -> character.Info
	3, // 10: character.Characters.Get:output_type -> character.CharData
	4, // 11: character.Characters.Delete:output_type -> character.Info
	2, // 12: character.Characters.Update:output_type -> character.Character
	3, // 13: character.Characters.GetAll:output_type -> character.CharData
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_character_proto_init() }
func file_proto_character_proto_init() {
	if File_proto_character_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_character_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Character); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_character_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_character_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_character_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_character_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_proto_character_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_proto_character_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_character_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_character_proto_goTypes,
		DependencyIndexes: file_proto_character_proto_depIdxs,
		EnumInfos:         file_proto_character_proto_enumTypes,
		MessageInfos:      file_proto_character_proto_msgTypes,
	}.Build()
	File_proto_character_proto = out.File
	file_proto_character_proto_rawDesc = nil
	file_proto_character_proto_goTypes = nil
	file_proto_character_proto_depIdxs = nil
}
